# Generated by Django 4.2.6 on 2023-10-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job Profile')),
                ('years_of_exp', models.IntegerField(verbose_name='Years of Experience')),
                ('main_tech', models.CharField(max_length=256, verbose_name='Main Technologies')),
                ('second_tech', models.CharField(max_length=254, verbose_name='Secondary Technologies')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_skills', models.CharField(max_length=50, verbose_name='Soft Skills')),
                ('team_exp', models.BooleanField(verbose_name='Team Experience')),
                ('methodologies', models.CharField(max_length=50, verbose_name='Methodologies')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('birthday', models.DateField(verbose_name='Date of Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=254, verbose_name='Phone Number')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCV',
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.userinfo', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.userinfo', verbose_name='User'),
        ),
    ]
