# Generated by Django 4.2.6 on 2023-10-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_jobinfo_skills_userinfo_delete_usercv_skills_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
    ]
