# Generated by Django 4.2.6 on 2023-10-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_remove_jobinfo_user_remove_skills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='team_exp',
            field=models.CharField(max_length=50, verbose_name='Team Experience'),
        ),
    ]
